spring:
  application:
    name: workshop

  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    
  rabbitmq:
    host: ${RABBIT_URL}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
  endpoint:
    health:
      show-details: always

app:
  toggleNotifications: true
  communicationsBackendUrl: "https://coms-microservice-899231617905.europe-southwest1.run.app/api/v1"

logging:
  file:
    name: logs/app.log