spring:
  application:
    name: workshop

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/users_db
    driver-class-name: org.postgresql.Driver
    username: dbuser
    password: 12345678A

  sql:
    init:
      schema-locations: classpath:/data/postgres/schema.sql
      data-locations: classpath:/data/postgres/data.sql
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

logging:
  file:
    name: logs/app.log
