spring:
  application:
    name: workshop

  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  sql:
    init:
      schema-locations: classpath:/data/postgres/schema.sql
      data-locations: classpath:/data/postgres/data.sql
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    
  rabbitmq:
    host: ${RABBIT_URL}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

app:
  toggleNotifications: false
  communicationsBackendUrl: "https://coms-microservice-899231617905.europe-southwest1.run.app/api/v1/"

logging:
  file:
    name: logs/app.log