spring:
  application:
    name: workshop

  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    
  rabbitmq:
    host: ${RABBIT_URL}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

  zipkin:
    base-url: "http://localhost:9411/"

  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  toggleNotifications: false
  communicationsBackendUrl: "https://coms-microservice-899231617905.europe-southwest1.run.app/api/v1"

logging:
  file:
    name: logs/app.log