spring:
  application:
    name: workshop

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

  sql:
    init:
      schema-locations: classpath:/data/h2/schema.sql
      data-locations: classpath:/data/h2/data.sql

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  file:
    name: logs/app.log
