spring:
  application:
    name: workshop

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/users_db
    driver-class-name: org.postgresql.Driver
    username: dbuser
    password: 12345678A

#  sql:
#    init:
#      schema-locations: classpath:/data/h2/schema.sql
#      data-locations: classpath:/data/h2/data.sql

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
